services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: finchat_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: gold
      CLICKHOUSE_USER: phglyxg
      CLICKHOUSE_PASSWORD: Phuongly1234
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
