# -*- coding: utf-8 -*-
"""audit_gold_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFIJ5G9aGCNwS3C20A9lmdD-reh22-wd

# Gold News Preprocessing & Relevance Analysis

## Objective

This notebook is used to evaluate the quality of the `gold_news` dataset, perform preprocessing, and assess whether the data is suitable for gold price analysis and chatbot retrieval.

The main objectives are:

- Inspect the crawled news data from VnExpress, Reuters, and Kitco.
- Identify missing content, duplicate articles, short articles, and irrelevant news.
- Create enriched features such as `quality_score`, `relevance_score`, `event_type`, `tags`, `symbols`, `sentiment_score`, and `impact_score`.
- Define which articles should be used for analysis, embedding, and RAG-based chatbot responses.

## Setup environment and import library
"""

!pip install pandas numpy rapidfuzz matplotlib seaborn python-dateutil tqdm

import pandas as pd
import numpy as np

import re
import html
import hashlib
import unicodedata
from datetime import datetime

from rapidfuzz import fuzz
from tqdm.auto import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

print("Environment is ready.")

"""## Load dataset"""

import os

os.listdir("/content")

DATA_PATH = "/content/gold_news.csv"

df = pd.read_csv(DATA_PATH)

print("Rows:", len(df))
print("Columns:", len(df.columns))
df.head()

"""## 1. Dataset Overview

The dataset used in this notebook is the `gold_news` table, which contains news articles crawled from multiple sources related to gold, financial markets, and macroeconomic events.

Current sources include:

- VnExpress: Vietnamese news, mainly useful for domestic gold market context.
- Reuters: international and macroeconomic news, which may include both directly and indirectly gold-related articles.
- Kitco: a specialized source for gold and precious metals.

In this section, we inspect the number of articles, source distribution, language distribution, and publication date coverage.
"""

# Check columns schema
print("Shape:", df.shape)

def count_missing_like(series):
    s = series.copy()

    # NaN / None
    missing_na = s.isna()

    # Empty string or "[]"
    missing_empty_text = s.astype(str).str.strip().isin(["", "[]", "None", "nan"])

    return (missing_na | missing_empty_text).sum()

schema_df = pd.DataFrame({
    "column": df.columns,
    "dtype": [df[col].dtype for col in df.columns],
    "missing_count": [count_missing_like(df[col]) for col in df.columns],
    "missing_rate": [round(count_missing_like(df[col]) / len(df), 4) for col in df.columns],
})

schema_df

"""### General statistics"""

total_articles = len(df)

audit_summary = {
    "total_articles": total_articles,
    "missing_title": count_missing_like(df["title"]),
    "missing_summary": count_missing_like(df["summary"]),
    "missing_content": count_missing_like(df["content"]),
    "missing_url": count_missing_like(df["url"]),
    "missing_published_at": count_missing_like(df["published_at"]),
    "missing_source_name": count_missing_like(df["source_name"]),
    "missing_canonical_url": count_missing_like(df["canonical_url"]),
}

pd.DataFrame([audit_summary]).T.rename(columns={0: "value"})

# Source name
if "source_name" in df.columns:
    source_count = (
        df["source_name"]
        .fillna("UNKNOWN")
        .value_counts()
        .reset_index()
    )
    source_count.columns = ["source_name", "article_count"]
    display(source_count)
else:
    print("Column source_name not found.")

# Language
if "language" in df.columns:
    language_count = (
        df["language"]
        .fillna("UNKNOWN")
        .value_counts()
        .reset_index()
    )
    language_count.columns = ["language", "article_count"]
    display(language_count)
else:
    print("Column language not found.")

# Check title = content
if {"title", "content"}.issubset(df.columns):
    title_eq_content = (
        df["title"].fillna("").str.strip()
        == df["content"].fillna("").str.strip()
    )

    print("Articles with title = content:", title_eq_content.sum())

    display(
        df.loc[title_eq_content, ["source_name", "title", "content", "url"]]
        .head(10)
    )
else:
    print("Missing title/content columns.")

# Check short content
if "content" in df.columns:
    df["content_len"] = df["content"].fillna("").astype(str).str.len()

    short_content_df = df[df["content_len"] < 50]

    print("Articles with content length < 50:", len(short_content_df))
    print("Rate:", round(len(short_content_df) / len(df), 4))

    display(
        short_content_df[["source_name", "title", "summary", "content", "content_len", "url"]]
        .head(10)
    )
else:
    print("Column content not found.")

# Check duplicate URL
if "canonical_url" in df.columns:
    duplicated_canonical_url = (
        df["canonical_url"]
        .dropna()
        .duplicated(keep=False)
    )

    print("Duplicated canonical_url rows:", duplicated_canonical_url.sum())

    display(
        df[df["canonical_url"].isin(
            df["canonical_url"][df["canonical_url"].duplicated(keep=False)].dropna()
        )][["source_name", "title", "canonical_url", "published_at"]]
        .sort_values("canonical_url")
        .head(20)
    )
else:
    print("Column canonical_url not found.")

# Check duplicate content_hash
if "content_hash" in df.columns:
    duplicated_content_hash = (
        df["content_hash"]
        .dropna()
        .duplicated(keep=False)
    )

    print("Duplicated content_hash rows:", duplicated_content_hash.sum())

    display(
        df[df["content_hash"].isin(
            df["content_hash"][df["content_hash"].duplicated(keep=False)].dropna()
        )][["source_name", "title", "content_hash", "published_at"]]
        .sort_values("content_hash")
        .head(20)
    )
else:
    print("Column content_hash not found.")

# Check date range
if "published_at" in df.columns:
    df["published_at_parsed"] = pd.to_datetime(df["published_at"], errors="coerce")

    print("Min published_at:", df["published_at_parsed"].min())
    print("Max published_at:", df["published_at_parsed"].max())
    print("Invalid published_at:", df["published_at_parsed"].isna().sum())

    articles_by_date = (
        df.dropna(subset=["published_at_parsed"])
        .assign(date=lambda x: x["published_at_parsed"].dt.date)
        .groupby("date")
        .size()
        .reset_index(name="article_count")
    )

    display(articles_by_date.head())
    display(articles_by_date.tail())
else:
    print("Column published_at not found.")

# Check suspicious old dates
old_date_df = df[df["published_at_parsed"] < "2024-01-01"].copy()

print("Old date rows:", len(old_date_df))

old_date_df[
    ["source_name", "title", "published_at", "published_at_parsed", "url"]
].sort_values("published_at_parsed").head(20)

"""Articles by date"""

if "published_at_parsed" in df.columns:
    articles_by_date = (
        df.dropna(subset=["published_at_parsed"])
        .assign(date=lambda x: x["published_at_parsed"].dt.date)
        .groupby("date")
        .size()
        .reset_index(name="article_count")
    )

    plt.figure(figsize=(14, 5))
    sns.lineplot(data=articles_by_date, x="date", y="article_count")
    plt.title("Number of Gold News Articles by Date")
    plt.xlabel("Date")
    plt.ylabel("Article Count")
    plt.xticks(rotation=45)
    plt.show()
else:
    print("Run the published_at parsing cell first.")

"""### Audit report"""

audit_report = {
    "total_articles": len(df),
    "sources": df["source_name"].fillna("UNKNOWN").value_counts().to_dict() if "source_name" in df.columns else {},
    "languages": df["language"].fillna("UNKNOWN").value_counts().to_dict() if "language" in df.columns else {},
    "missing_title": int(df["title"].isna().sum()) if "title" in df.columns else None,
    "missing_summary": int(df["summary"].isna().sum()) if "summary" in df.columns else None,
    "missing_content": int(df["content"].isna().sum()) if "content" in df.columns else None,
    "short_content_lt_50": int((df["content"].fillna("").astype(str).str.len() < 50).sum()) if "content" in df.columns else None,
    "missing_published_at": int(df["published_at"].isna().sum()) if "published_at" in df.columns else None,
    "duplicated_canonical_url_rows": int(df["canonical_url"].dropna().duplicated(keep=False).sum()) if "canonical_url" in df.columns else None,
    "duplicated_content_hash_rows": int(df["content_hash"].dropna().duplicated(keep=False).sum()) if "content_hash" in df.columns else None,
}

audit_report

"""### Observation

The dataset contains articles from both domestic and international sources. Reuters and Kitco provide global market context, while VnExpress adds local Vietnamese gold market information.

If one source dominates the dataset, additional filtering may be needed to avoid source bias in downstream analysis and retrieval.

### 2. Clean Text Fields

In this step, we clean the main text fields:
```
- title
- summary
- content
```
The goal is to normalize text before hashing, deduplication, relevance scoring, sentiment scoring, and embedding.
"""

def clean_text(text):
    """
    Clean raw text from crawled news data.

    Rules:
    - Convert None/NaN to empty string
    - Normalize unicode
    - Unescape HTML entities
    - Remove HTML tags
    - Normalize spaces and newlines
    - Strip leading/trailing spaces
    """
    if pd.isna(text):
        return ""

    text = str(text)

    # Normalize unicode
    text = unicodedata.normalize("NFKC", text)

    # Unescape HTML entities, e.g. &amp; -> &
    text = html.unescape(text)

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove common invisible characters
    text = text.replace("\xa0", " ")
    text = text.replace("\u200b", " ")

    # Normalize newlines
    text = re.sub(r"\r\n|\r", "\n", text)

    # Collapse multiple spaces/tabs
    text = re.sub(r"[ \t]+", " ", text)

    # Collapse too many newlines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()

# Test
sample_texts = [
    None,
    "",
    "   Giá vàng     hôm nay tăng mạnh   ",
    "Gold &amp; silver prices <b>rise</b> today",
    "Dòng 1\n\n\n\nDòng 2",
]

for text in sample_texts:
    print("RAW:  ", repr(text))
    print("CLEAN:", repr(clean_text(text)))
    print("-" * 80)

# Create copy for preprocessing
df_clean = df.copy()

for col in ["title", "summary", "content"]:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].apply(clean_text)

df_clean[["title", "summary", "content"]].head()

compare_cols = ["source_name", "title", "summary", "content"]

sample_compare = pd.DataFrame({
    "source_name": df["source_name"].head(10),
    "title_raw": df["title"].head(10),
    "title_clean": df_clean["title"].head(10),
    "content_raw": df["content"].head(10),
    "content_clean": df_clean["content"].head(10),
})

sample_compare

"""### Recomputing length after clean"""

df_clean["title_len"] = df_clean["title"].fillna("").astype(str).str.len()
df_clean["summary_len"] = df_clean["summary"].fillna("").astype(str).str.len()
df_clean["content_len"] = df_clean["content"].fillna("").astype(str).str.len()

text_length_summary = {
    "empty_title_after_clean": int((df_clean["title_len"] == 0).sum()),
    "empty_summary_after_clean": int((df_clean["summary_len"] == 0).sum()),
    "empty_content_after_clean": int((df_clean["content_len"] == 0).sum()),
    "short_content_lt_50_after_clean": int((df_clean["content_len"] < 50).sum()),
    "short_content_lt_200_after_clean": int((df_clean["content_len"] < 200).sum()),
}

text_length_summary

html_tag_pattern = r"<[^>]+>"

html_leftover = pd.DataFrame({
    "title_has_html": df_clean["title"].str.contains(html_tag_pattern, regex=True, na=False),
    "summary_has_html": df_clean["summary"].str.contains(html_tag_pattern, regex=True, na=False),
    "content_has_html": df_clean["content"].str.contains(html_tag_pattern, regex=True, na=False),
})

html_leftover.sum()

"""## 3. Normalize URL and Recompute Hashes

After cleaning text, we recompute stable hashes for deduplication.

We will create:
```
- canonical_url
- title_hash
- content_hash
- article_id
```
"""

def normalize_url(url):
    """
    Normalize URL for stable deduplication.

    MVP rule:
    - Convert NaN/None to empty string
    - Strip spaces
    - Remove query string
    - Remove URL fragment
    """
    if pd.isna(url):
        return ""

    url = str(url).strip()

    if not url:
        return ""

    url = url.split("?")[0]
    url = url.split("#")[0]

    return url

def sha256_text(text):
    """
    Generate SHA256 hash from text.
    """
    if pd.isna(text):
        text = ""

    text = str(text)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

"""### Recompute canonical_url"""

df_clean["canonical_url_new"] = df_clean.apply(
    lambda row: normalize_url(row["canonical_url"])
    if "canonical_url" in df_clean.columns and clean_text(row.get("canonical_url", "")) != ""
    else normalize_url(row.get("url", "")),
    axis=1
)

df_clean[["url", "canonical_url", "canonical_url_new"]].head()

"""### Recompute title_hash"""

df_clean["title_hash_new"] = df_clean["title"].apply(
    lambda x: sha256_text(clean_text(x)) if clean_text(x) else ""
)

print("Empty title_hash_new:", (df_clean["title_hash_new"] == "").sum())

df_clean[["title", "title_hash_new"]].head()

def generate_content_hash(row):
    content = clean_text(row.get("content", ""))
    title = clean_text(row.get("title", ""))
    summary = clean_text(row.get("summary", ""))
    canonical_url = clean_text(row.get("canonical_url_new", ""))

    if content and len(content) >= 50:
        hash_input = content
    else:
        hash_input = title + " " + summary + " " + canonical_url

    return sha256_text(hash_input)


df_clean["content_hash_new"] = df_clean.apply(generate_content_hash, axis=1)

print("Empty content_hash_new:", (df_clean["content_hash_new"] == "").sum())

df_clean[["title", "content_len", "content_hash_new"]].head()

"""### Recompute article id"""

def generate_article_id(row):
    canonical_url = clean_text(row.get("canonical_url_new", ""))

    if canonical_url:
        return sha256_text(canonical_url)

    fallback = (
        clean_text(row.get("title", ""))
        + " "
        + clean_text(row.get("summary", ""))
        + " "
        + clean_text(str(row.get("published_at", "")))
    )

    return sha256_text(fallback)


df_clean["id_new"] = df_clean.apply(generate_article_id, axis=1)

print("Empty id_new:", (df_clean["id_new"] == "").sum())
print("Duplicated id_new rows:", df_clean["id_new"].duplicated(keep=False).sum())

df_clean[["source_name", "title", "id_new"]].head()

hash_compare = {}

if "content_hash" in df_clean.columns:
    hash_compare["content_hash_changed"] = int(
        (df_clean["content_hash"].fillna("") != df_clean["content_hash_new"].fillna("")).sum()
    )

if "title_hash" in df_clean.columns:
    hash_compare["title_hash_changed"] = int(
        (df_clean["title_hash"].fillna("") != df_clean["title_hash_new"].fillna("")).sum()
    )

if "id" in df_clean.columns:
    hash_compare["id_changed"] = int(
        (df_clean["id"].fillna("") != df_clean["id_new"].fillna("")).sum()
    )

hash_compare

df_clean["canonical_url"] = df_clean["canonical_url_new"]
df_clean["title_hash"] = df_clean["title_hash_new"]
df_clean["content_hash"] = df_clean["content_hash_new"]
df_clean["id"] = df_clean["id_new"]

df_clean = df_clean.drop(
    columns=[
        "canonical_url_new",
        "title_hash_new",
        "content_hash_new",
        "id_new",
    ],
    errors="ignore"
)

df_clean[["id", "title_hash", "content_hash", "canonical_url"]].head()

hash_audit_after = {
    "empty_id": int((df_clean["id"].fillna("").astype(str).str.len() == 0).sum()),
    "empty_title_hash": int((df_clean["title_hash"].fillna("").astype(str).str.len() == 0).sum()),
    "empty_content_hash": int((df_clean["content_hash"].fillna("").astype(str).str.len() == 0).sum()),
    "duplicated_id_rows": int(df_clean["id"].duplicated(keep=False).sum()),
    "duplicated_title_hash_rows": int(df_clean["title_hash"].duplicated(keep=False).sum()),
    "duplicated_content_hash_rows": int(df_clean["content_hash"].duplicated(keep=False).sum()),
}

hash_audit_after

"""### Observation

Some articles have missing or very short content. This usually means the crawler only captured a headline, RSS snippet, or article preview instead of the full article body.

These articles should not be removed immediately, but they should receive a lower `quality_score` and should not be used for deep causal analysis.

## 4. Duplicate Detection

In this step, we detect duplicate articles.

We do not delete duplicated rows in the MVP.  
We only mark duplicated articles using the `is_duplicate` field.

Deduplication rules:

1. Same canonical URL
2. Same content hash
3. Same title hash on the same date
4. Very similar title on the same date

Raw news → Clean text → Hash/Dedupe → Quality scoring → Relevance scoring → Event classification → Sentiment/Impact scoring → Enriched news
"""

df_clean["published_at_parsed"] = pd.to_datetime(
    df_clean["published_at"],
    errors="coerce"
)

df_clean["published_date"] = df_clean["published_at_parsed"].dt.date

df_clean[["source_name", "title", "published_at", "published_date"]].head()

df_clean["is_duplicate"] = False
df_clean["duplicate_reason"] = ""

url_dup_mask = (
    df_clean["canonical_url"].fillna("").ne("")
    & df_clean["canonical_url"].duplicated(keep="first")
)

df_clean.loc[url_dup_mask, "is_duplicate"] = True
df_clean.loc[url_dup_mask, "duplicate_reason"] = "duplicate_canonical_url"

print("Duplicate by canonical_url:", int(url_dup_mask.sum()))

content_hash_dup_mask = (
    df_clean["content_hash"].fillna("").ne("")
    & df_clean["content_hash"].duplicated(keep="first")
)

df_clean.loc[content_hash_dup_mask, "is_duplicate"] = True
df_clean.loc[
    content_hash_dup_mask & df_clean["duplicate_reason"].eq(""),
    "duplicate_reason"
] = "duplicate_content_hash"

print("Duplicate by content_hash:", int(content_hash_dup_mask.sum()))

title_hash_dup_mask = (
    df_clean["title_hash"].fillna("").ne("")
    & df_clean.duplicated(
        subset=["published_date", "title_hash"],
        keep="first"
    )
)

df_clean.loc[title_hash_dup_mask, "is_duplicate"] = True
df_clean.loc[
    title_hash_dup_mask & df_clean["duplicate_reason"].eq(""),
    "duplicate_reason"
] = "duplicate_title_hash_same_day"

print("Duplicate by title_hash same day:", int(title_hash_dup_mask.sum()))

def mark_similar_title_duplicates(df, threshold=90):
    """
    Mark articles as duplicate if their titles are very similar on the same date.

    This is an MVP implementation for notebook use.
    """
    df = df.copy()

    for published_date, group in tqdm(df.groupby("published_date"), desc="Checking similar titles"):
        seen_titles = []

        for idx, row in group.iterrows():
            title = clean_text(row.get("title", "")).lower()

            if not title:
                continue

            already_duplicate = bool(df.at[idx, "is_duplicate"])
            if already_duplicate:
                continue

            matched = False

            for seen_title in seen_titles:
                score = fuzz.ratio(title, seen_title)

                if score >= threshold:
                    df.at[idx, "is_duplicate"] = True
                    df.at[idx, "duplicate_reason"] = "similar_title_same_day"
                    matched = True
                    break

            if not matched:
                seen_titles.append(title)

    return df


df_clean = mark_similar_title_duplicates(df_clean, threshold=90)

print("Total duplicates after similar-title check:", int(df_clean["is_duplicate"].sum()))

duplicate_summary = (
    df_clean["duplicate_reason"]
    .replace("", "not_duplicate")
    .value_counts()
    .reset_index()
)

duplicate_summary.columns = ["duplicate_reason", "article_count"]
duplicate_summary

title_dup_debug = df_clean[
    df_clean["title_hash"].fillna("").ne("")
    & df_clean["title_hash"].duplicated(keep=False)
][
    ["source_name", "published_date", "title", "title_hash"]
].sort_values(["title_hash", "published_date"])

title_dup_debug.head(50)

"""## 5. Quality Score

In this step, we compute a quality score for each article.

The score ranges from `0.0` to `1.0`.

A high-quality article usually has:

- valid title
- valid summary
- valid content
- valid published_at
- source name
- content that is long enough for analysis

Reuters/RSS articles often have short or missing content, so they use a separate scoring rule.
"""

# Direct gold-related keywords: English + Vietnamese
DIRECT_GOLD_KEYWORDS = [
    # English
    "gold",
    "xauusd",
    "xau/usd",
    "bullion",
    "precious metal",
    "precious metals",
    "spot gold",
    "gold futures",
    "gold price",
    "gold prices",
    "gold market",
    "comex gold",
    "safe-haven gold",

    # Vietnamese
    "giá vàng",
    "vàng",
    "vàng miếng",
    "vàng nhẫn",
    "vàng sjc",
    "sjc",
    "doji",
    "pnj",
    "bảo tín minh châu",
    "btmc",
    "vàng thế giới",
    "vàng trong nước",
    "kim loại quý",
]

# Macro keywords that can affect gold: English + Vietnamese
MACRO_KEYWORDS = [
    # English - monetary policy
    "fed",
    "federal reserve",
    "fomc",
    "interest rate",
    "interest rates",
    "rate cut",
    "rate cuts",
    "rate hike",
    "rate hikes",
    "monetary policy",
    "hawkish",
    "dovish",

    # English - inflation / labor / economy
    "inflation",
    "cpi",
    "pce",
    "core pce",
    "nfp",
    "nonfarm payrolls",
    "jobs report",
    "unemployment",
    "recession",
    "economic slowdown",
    "gdp",

    # English - USD / yields
    "usd",
    "u.s. dollar",
    "us dollar",
    "dollar",
    "dxy",
    "treasury yield",
    "treasury yields",
    "bond yield",
    "bond yields",
    "10-year yield",
    "real yield",
    "real yields",

    # English - risk / geopolitics
    "safe haven",
    "safe-haven",
    "geopolitical",
    "war",
    "conflict",
    "middle east",
    "ukraine",
    "russia",
    "tariff",
    "trade war",
    "central bank",

    # Vietnamese - monetary policy
    "cục dự trữ liên bang",
    "fed",
    "fomc",
    "lãi suất",
    "cắt giảm lãi suất",
    "giảm lãi suất",
    "tăng lãi suất",
    "chính sách tiền tệ",
    "diều hâu",
    "ôn hòa",

    # Vietnamese - inflation / economy
    "lạm phát",
    "cpi",
    "pce",
    "bảng lương phi nông nghiệp",
    "việc làm",
    "thất nghiệp",
    "suy thoái",
    "tăng trưởng kinh tế",
    "gdp",

    # Vietnamese - USD / yields
    "usd",
    "đồng usd",
    "đô la",
    "đồng đôla",
    "đồng bạc xanh",
    "dxy",
    "lợi suất trái phiếu",
    "trái phiếu kho bạc",
    "lợi suất kho bạc",
    "lợi suất mỹ",

    # Vietnamese - risk / geopolitics
    "trú ẩn an toàn",
    "tài sản trú ẩn",
    "địa chính trị",
    "chiến tranh",
    "xung đột",
    "trung đông",
    "ukraine",
    "nga",
    "thuế quan",
    "chiến tranh thương mại",
    "ngân hàng trung ương",
]

# Noise keywords: contains "gold" but not commodity gold
GOLD_NOISE_KEYWORDS = [
    # English
    "gold card",
    "gold visa",
    "golden visa",
    "gold medal",
    "gold medals",
    "gold award",
    "gold awards",
    "golden globe",
    "goldman",
    "goldman sachs",

    # Vietnamese
    "thẻ vàng",
    "thẻ vàng eu",
    "huy chương vàng",
    "quả cầu vàng",
    "giải vàng",
]

def normalize_for_keyword(text):
    text = clean_text(text).lower()
    text = unicodedata.normalize("NFKC", text)
    return text


def contains_any_keyword(text, keywords):
    text = normalize_for_keyword(text)
    return any(keyword.lower() in text for keyword in keywords)


def count_keywords(text, keywords):
    text = normalize_for_keyword(text)
    return sum(1 for keyword in keywords if keyword.lower() in text)

def compute_quality_score(row):
    title = clean_text(row.get("title", ""))
    summary = clean_text(row.get("summary", ""))
    content = clean_text(row.get("content", ""))
    source_name = clean_text(row.get("source_name", ""))
    source_type = clean_text(row.get("source_type", "")).lower()
    published_at = row.get("published_at_parsed", pd.NaT)

    title_lower = title.lower()
    content_len = len(content)

    # Reuters/RSS rule: useful for macro overview, but weak for deep RAG
    is_reuters_rss = (
        source_name.lower() == "reuters"
        or source_type == "rss"
    )

    if is_reuters_rss and content_len < 200:
        score = 0.30

        if contains_any_keyword(title_lower, DIRECT_GOLD_KEYWORDS):
            score += 0.10

        if contains_any_keyword(title_lower, MACRO_KEYWORDS):
            score += 0.05

        if pd.notna(published_at):
            score += 0.05

        return round(min(score, 0.50), 4)

    # General full-article rule
    score = 0.0

    if len(title) > 0:
        score += 0.20

    if len(summary) > 0:
        score += 0.10

    if pd.notna(published_at):
        score += 0.10

    if title and content and title.strip() != content.strip():
        score += 0.10

    if source_name:
        score += 0.10

    if content_len >= 800:
        score += 0.40
    elif content_len >= 200:
        score += 0.25
    elif content_len >= 50:
        score += 0.10
    else:
        score += 0.00

    return round(min(max(score, 0.0), 1.0), 4)

df_clean["quality_score"] = df_clean.apply(compute_quality_score, axis=1)

df_clean[[
    "source_name",
    "title",
    "content_len",
    "quality_score"
]].head(20)

quality_summary = df_clean["quality_score"].describe()
quality_summary

quality_by_source = (
    df_clean
    .groupby("source_name")
    .agg(
        total_articles=("id", "count"),
        avg_quality=("quality_score", "mean"),
        min_quality=("quality_score", "min"),
        max_quality=("quality_score", "max"),
        articles_quality_ge_035=("quality_score", lambda x: int((x >= 0.35).sum())),
        articles_quality_ge_050=("quality_score", lambda x: int((x >= 0.50).sum())),
    )
    .reset_index()
)

quality_by_source["avg_quality"] = quality_by_source["avg_quality"].round(4)

quality_by_source

plt.figure(figsize=(10, 5))
sns.histplot(df_clean["quality_score"], bins=20, kde=True)
plt.title("Quality Score Distribution")
plt.xlabel("Quality Score")
plt.ylabel("Article Count")
plt.show()

low_quality_articles = df_clean[df_clean["quality_score"] < 0.35][
    [
        "source_name",
        "title",
        "summary",
        "content_len",
        "quality_score",
        "published_at",
        "url",
    ]
].sort_values("quality_score")

low_quality_articles.head(30)

high_quality_articles = df_clean[df_clean["quality_score"] >= 0.50][
    [
        "source_name",
        "title",
        "summary",
        "content_len",
        "quality_score",
        "published_at",
        "url",
    ]
].sort_values("quality_score", ascending=False)

high_quality_articles.head(30)

"""### Observation

The quality score distribution shows that some articles have very short content. These articles may still be useful if their title and summary are relevant, but they should receive lower priority during retrieval.

For deeper analysis, articles with higher `quality_score` should be preferred.

## 6. Relevance Score

In this step, we compute whether each article is relevant to gold price analysis.

The relevance score ranges from 0.0 to 1.0.

Main rules:

- Direct gold news should have high relevance.
- Macro news about Fed, CPI, USD, yields, and geopolitics can have medium relevance.
- Articles that mention "gold" but are not about commodity gold should be penalized.
"""

DIRECT_GOLD_KEYWORDS = [
    # English
    "gold",
    "gold price",
    "gold prices",
    "spot gold",
    "gold futures",
    "bullion",
    "precious metal",
    "precious metals",
    "xauusd",
    "xau/usd",
    "comex gold",

    # Vietnamese
    "giá vàng",
    "vàng miếng",
    "vàng nhẫn",
    "vàng sjc",
    "vàng thế giới",
    "vàng trong nước",
    "kim loại quý",
    "sjc",
    "doji",
    "pnj",
    "bảo tín minh châu",
    "btmc",
]

DOMESTIC_GOLD_KEYWORDS = [
    "sjc",
    "doji",
    "pnj",
    "bảo tín minh châu",
    "btmc",
    "vàng miếng",
    "vàng nhẫn",
    "vàng trong nước",
    "giá vàng trong nước",
]

MACRO_GOLD_KEYWORDS = [
    # English
    "fed",
    "federal reserve",
    "fomc",
    "interest rate",
    "interest rates",
    "rate cut",
    "rate cuts",
    "rate hike",
    "rate hikes",
    "inflation",
    "cpi",
    "pce",
    "core pce",
    "nfp",
    "nonfarm payrolls",
    "jobs report",
    "unemployment",
    "usd",
    "u.s. dollar",
    "us dollar",
    "dollar",
    "dxy",
    "treasury yield",
    "treasury yields",
    "bond yield",
    "bond yields",
    "10-year yield",
    "real yield",
    "safe haven",
    "safe-haven",
    "geopolitical",
    "war",
    "conflict",
    "tariff",
    "trade war",
    "recession",
    "central bank",

    # Vietnamese
    "cục dự trữ liên bang",
    "lãi suất",
    "cắt giảm lãi suất",
    "giảm lãi suất",
    "tăng lãi suất",
    "chính sách tiền tệ",
    "lạm phát",
    "việc làm",
    "thất nghiệp",
    "suy thoái",
    "đồng usd",
    "đô la",
    "đồng đôla",
    "đồng bạc xanh",
    "lợi suất trái phiếu",
    "trái phiếu kho bạc",
    "trú ẩn an toàn",
    "tài sản trú ẩn",
    "địa chính trị",
    "chiến tranh",
    "xung đột",
    "thuế quan",
    "chiến tranh thương mại",
    "ngân hàng trung ương",
]

GOLD_NOISE_KEYWORDS = [
    # English
    "gold card",
    "gold visa",
    "golden visa",
    "gold medal",
    "gold medals",
    "gold award",
    "gold awards",
    "golden globe",
    "goldman",
    "goldman sachs",

    # Vietnamese
    "thẻ vàng",
    "huy chương vàng",
    "quả cầu vàng",
    "giải vàng",
]

def normalize_for_keyword(text):
    text = clean_text(text).lower()
    text = unicodedata.normalize("NFKC", text)
    return text


def contains_any_keyword(text, keywords):
    text = normalize_for_keyword(text)
    return any(keyword.lower() in text for keyword in keywords)


def count_keywords(text, keywords):
    text = normalize_for_keyword(text)
    return sum(1 for keyword in keywords if keyword.lower() in text)

def compute_relevance_score(row):
    title = clean_text(row.get("title", ""))
    summary = clean_text(row.get("summary", ""))
    content = clean_text(row.get("content", ""))

    title_text = title.lower()
    summary_text = summary.lower()
    content_text = content.lower()
    full_text = f"{title_text} {summary_text} {content_text}"

    score = 0.0

    # Strong penalty for noise articles
    if contains_any_keyword(full_text, GOLD_NOISE_KEYWORDS):
        return 0.05

    # Direct gold in title is strongest
    if contains_any_keyword(title_text, DIRECT_GOLD_KEYWORDS):
        score += 0.60

    # Direct gold in summary/content
    if contains_any_keyword(summary_text, DIRECT_GOLD_KEYWORDS):
        score += 0.20

    if contains_any_keyword(content_text, DIRECT_GOLD_KEYWORDS):
        score += 0.20

    # Domestic gold
    if contains_any_keyword(full_text, DOMESTIC_GOLD_KEYWORDS):
        score += 0.15

    # Macro relevance
    macro_count_title = count_keywords(title_text, MACRO_GOLD_KEYWORDS)
    macro_count_full = count_keywords(full_text, MACRO_GOLD_KEYWORDS)

    if macro_count_title > 0:
        score += min(0.25, macro_count_title * 0.08)

    if macro_count_full > 0:
        score += min(0.25, macro_count_full * 0.04)

    # Very short generic Reuters/category pages should be penalized
    generic_noise_titles = [
        "breaking international news",
        "global market headlines",
        "top energy headlines",
        "stock market news",
    ]

    if contains_any_keyword(title_text, generic_noise_titles):
        score = min(score, 0.15)

    return round(min(max(score, 0.0), 1.0), 4)


def is_relevant(score, threshold=0.35):
    return score >= threshold

NEWS_RELEVANCE_THRESHOLD = 0.35

df_clean["relevance_score"] = df_clean.apply(compute_relevance_score, axis=1)
df_clean["is_relevant"] = df_clean["relevance_score"].apply(
    lambda x: is_relevant(x, NEWS_RELEVANCE_THRESHOLD)
)

df_clean[[
    "source_name",
    "title",
    "quality_score",
    "relevance_score",
    "is_relevant"
]].head(30)

relevance_by_source = (
    df_clean
    .groupby("source_name")
    .agg(
        total_articles=("id", "count"),
        relevant_articles=("is_relevant", "sum"),
        avg_relevance=("relevance_score", "mean"),
        min_relevance=("relevance_score", "min"),
        max_relevance=("relevance_score", "max"),
    )
    .reset_index()
)

relevance_by_source["relevant_rate"] = (
    relevance_by_source["relevant_articles"]
    / relevance_by_source["total_articles"]
).round(4)

relevance_by_source["avg_relevance"] = relevance_by_source["avg_relevance"].round(4)

relevance_by_source

not_relevant_sample = df_clean[df_clean["is_relevant"] == False][
    [
        "source_name",
        "title",
        "summary",
        "quality_score",
        "relevance_score",
        "url",
    ]
].sort_values("relevance_score")

not_relevant_sample.head(30)

high_relevance_sample = df_clean[df_clean["relevance_score"] >= 0.70][
    [
        "source_name",
        "title",
        "summary",
        "quality_score",
        "relevance_score",
        "url",
    ]
].sort_values("relevance_score", ascending=False)

high_relevance_sample.head(30)

plt.figure(figsize=(10, 5))
sns.histplot(df_clean["relevance_score"], bins=20, kde=True)
plt.title("Relevance Score Distribution")
plt.xlabel("Relevance Score")
plt.ylabel("Article Count")
plt.show()

"""### 7. Extract Symbols, Tags, and Entities

In this step, we extract simple metadata from each news article.

We create:

- symbols: standardized market/entity symbols such as GOLD, XAUUSD, SJC, USD, FED
- tags: topic labels such as gold_price, domestic_gold, fed, inflation
- entities: simple entity strings such as Fed, SJC, USD, Vietnam

This is rule-based for the MVP.
"""

SYMBOL_RULES = {
    "GOLD": [
        "gold", "giá vàng", "vàng", "bullion", "precious metal", "precious metals",
        "spot gold", "gold futures", "kim loại quý"
    ],
    "XAUUSD": [
        "xauusd", "xau/usd", "spot gold"
    ],
    "SJC": [
        "sjc", "vàng sjc", "vàng miếng"
    ],
    "USD": [
        "usd", "u.s. dollar", "us dollar", "dollar", "đồng usd", "đô la",
        "đồng đôla", "đồng bạc xanh"
    ],
    "DXY": [
        "dxy", "dollar index", "chỉ số đô la", "chỉ số dollar"
    ],
    "US10Y": [
        "10-year yield", "treasury yield", "treasury yields", "bond yield",
        "bond yields", "lợi suất trái phiếu", "trái phiếu kho bạc",
        "lợi suất kho bạc"
    ],
    "FED": [
        "fed", "federal reserve", "fomc", "cục dự trữ liên bang"
    ],
    "CPI": [
        "cpi", "consumer price index", "lạm phát"
    ],
    "PCE": [
        "pce", "core pce"
    ],
    "NFP": [
        "nfp", "nonfarm payrolls", "jobs report", "bảng lương phi nông nghiệp"
    ],
    "VND": [
        "vnd", "đồng", "việt nam", "trong nước"
    ],
    "PNJ": [
        "pnj"
    ],
    "DOJI": [
        "doji"
    ],
    "BTMC": [
        "bảo tín minh châu", "btmc"
    ],
}

TAG_RULES = {
    "gold_price": [
        "gold price", "gold prices", "giá vàng", "spot gold", "gold futures"
    ],
    "domestic_gold": [
        "vàng trong nước", "vàng miếng", "vàng nhẫn", "sjc", "doji", "pnj",
        "bảo tín minh châu", "btmc"
    ],
    "world_gold": [
        "world gold", "global gold", "vàng thế giới", "spot gold", "comex gold"
    ],
    "sjc": [
        "sjc", "vàng sjc", "vàng miếng"
    ],
    "gold_ring": [
        "vàng nhẫn", "nhẫn trơn"
    ],
    "fed": [
        "fed", "federal reserve", "fomc", "cục dự trữ liên bang"
    ],
    "interest_rate": [
        "interest rate", "interest rates", "rate cut", "rate cuts", "rate hike",
        "rate hikes", "lãi suất", "cắt giảm lãi suất", "giảm lãi suất", "tăng lãi suất"
    ],
    "usd": [
        "usd", "u.s. dollar", "us dollar", "dollar", "đồng usd", "đô la",
        "đồng đôla", "đồng bạc xanh"
    ],
    "dxy": [
        "dxy", "dollar index"
    ],
    "inflation": [
        "inflation", "lạm phát"
    ],
    "cpi": [
        "cpi", "consumer price index"
    ],
    "pce": [
        "pce", "core pce"
    ],
    "nfp": [
        "nfp", "nonfarm payrolls", "jobs report", "bảng lương phi nông nghiệp"
    ],
    "bond_yield": [
        "treasury yield", "treasury yields", "bond yield", "bond yields",
        "10-year yield", "lợi suất trái phiếu", "trái phiếu kho bạc"
    ],
    "geopolitical": [
        "geopolitical", "war", "conflict", "địa chính trị", "chiến tranh", "xung đột"
    ],
    "safe_haven": [
        "safe haven", "safe-haven", "trú ẩn an toàn", "tài sản trú ẩn"
    ],
    "tariff": [
        "tariff", "trade war", "thuế quan", "chiến tranh thương mại"
    ],
    "central_bank": [
        "central bank", "central banks", "ngân hàng trung ương"
    ],
    "stock_market": [
        "stock market", "stocks", "equities", "chứng khoán", "cổ phiếu"
    ],
    "oil": [
        "oil", "crude", "brent", "wti", "dầu"
    ],
    "crypto": [
        "crypto", "bitcoin", "btc", "tiền số", "tiền mã hóa"
    ],
}

ENTITY_RULES = {
    "Fed": ["fed", "federal reserve", "fomc", "cục dự trữ liên bang"],
    "SJC": ["sjc", "vàng sjc"],
    "DOJI": ["doji"],
    "PNJ": ["pnj"],
    "Bao Tin Minh Chau": ["bảo tín minh châu", "btmc"],
    "USD": ["usd", "u.s. dollar", "us dollar", "dollar", "đồng usd", "đồng bạc xanh"],
    "DXY": ["dxy", "dollar index"],
    "CPI": ["cpi", "consumer price index"],
    "PCE": ["pce", "core pce"],
    "NFP": ["nfp", "nonfarm payrolls", "jobs report", "bảng lương phi nông nghiệp"],
    "Gold": ["gold", "giá vàng", "vàng", "bullion"],
    "Vietnam": ["việt nam", "vietnam", "trong nước"],
    "China": ["china", "trung quốc"],
    "Russia": ["russia", "nga"],
    "Ukraine": ["ukraine"],
    "Middle East": ["middle east", "trung đông"],
}

def build_article_text(row):
    title = clean_text(row.get("title", ""))
    summary = clean_text(row.get("summary", ""))
    content = clean_text(row.get("content", ""))
    return f"{title} {summary} {content}"


def extract_by_rules(text, rules):
    text = normalize_for_keyword(text)
    results = []

    for label, keywords in rules.items():
        if contains_any_keyword(text, keywords):
            results.append(label)

    return sorted(set(results))


def extract_symbols(row):
    text = build_article_text(row)
    return extract_by_rules(text, SYMBOL_RULES)


def extract_tags(row):
    text = build_article_text(row)
    return extract_by_rules(text, TAG_RULES)


def extract_entities(row):
    text = build_article_text(row)
    return extract_by_rules(text, ENTITY_RULES)

df_clean["symbols"] = df_clean.apply(extract_symbols, axis=1)
df_clean["tags"] = df_clean.apply(extract_tags, axis=1)
df_clean["entities"] = df_clean.apply(extract_entities, axis=1)

df_clean[[
    "source_name",
    "title",
    "symbols",
    "tags",
    "entities",
    "relevance_score",
    "is_relevant"
]].head(30)

def add_fallback_tags(row):
    tags = set(row.get("tags", []))
    symbols = set(row.get("symbols", []))
    text = build_article_text(row)

    # If article is relevant and related to gold, make sure it has basic gold tag
    if row.get("is_relevant", False) and "GOLD" in symbols:
        tags.add("gold_price")

    # Domestic gold fallback
    if any(symbol in symbols for symbol in ["SJC", "DOJI", "PNJ", "BTMC", "VND"]):
        tags.add("domestic_gold")

    # Macro fallback from symbols
    if "FED" in symbols:
        tags.add("fed")

    if "USD" in symbols:
        tags.add("usd")

    if "DXY" in symbols:
        tags.add("dxy")

    if "US10Y" in symbols:
        tags.add("bond_yield")

    if "CPI" in symbols:
        tags.add("cpi")
        tags.add("inflation")

    if "PCE" in symbols:
        tags.add("pce")
        tags.add("inflation")

    if "NFP" in symbols:
        tags.add("nfp")

    # World gold fallback
    if contains_any_keyword(text, ["spot gold", "gold futures", "comex gold", "vàng thế giới"]):
        tags.add("world_gold")

    return sorted(tags)


df_clean["tags"] = df_clean.apply(add_fallback_tags, axis=1)

metadata_audit = {
    "empty_symbols": int(df_clean["symbols"].apply(lambda x: len(x) == 0).sum()),
    "empty_tags": int(df_clean["tags"].apply(lambda x: len(x) == 0).sum()),
    "empty_entities": int(df_clean["entities"].apply(lambda x: len(x) == 0).sum()),
    "empty_symbols_relevant_articles": int(
        df_clean[df_clean["is_relevant"]]["symbols"].apply(lambda x: len(x) == 0).sum()
    ),
    "empty_tags_relevant_articles": int(
        df_clean[df_clean["is_relevant"]]["tags"].apply(lambda x: len(x) == 0).sum()
    ),
}

metadata_audit

from collections import Counter

symbol_counter = Counter()

for symbols in df_clean["symbols"]:
    symbol_counter.update(symbols)

top_symbols = pd.DataFrame(
    symbol_counter.most_common(30),
    columns=["symbol", "article_count"]
)

top_symbols

tag_counter = Counter()

for tags in df_clean["tags"]:
    tag_counter.update(tags)

top_tags = pd.DataFrame(
    tag_counter.most_common(30),
    columns=["tag", "article_count"]
)

top_tags

relevant_missing_metadata = df_clean[
    (df_clean["is_relevant"] == True)
    & (
        (df_clean["symbols"].apply(lambda x: len(x) == 0))
        | (df_clean["tags"].apply(lambda x: len(x) == 0))
    )
][
    [
        "source_name",
        "title",
        "summary",
        "relevance_score",
        "symbols",
        "tags",
        "entities",
        "url",
    ]
]

print("Relevant articles missing symbols/tags:", len(relevant_missing_metadata))
relevant_missing_metadata.head(30)

df_clean[
    df_clean["symbols"].apply(lambda symbols: "SJC" in symbols)
][
    [
        "source_name",
        "title",
        "symbols",
        "tags",
        "entities",
        "relevance_score",
    ]
].head(30)

df_clean[
    df_clean["symbols"].apply(lambda symbols: ("FED" in symbols) or ("USD" in symbols))
][
    [
        "source_name",
        "title",
        "symbols",
        "tags",
        "entities",
        "relevance_score",
    ]
].head(30)

"""### 8. Classify Event Type

In this step, we classify each article into one main event type.

Event types:

- gold_price_update
- fed_policy
- inflation_data
- usd_movement
- bond_yield
- geopolitical_risk
- tariff_trade
- domestic_market
- central_bank_demand
- economic_growth
- stock_market_risk
- other
"""

EVENT_TYPE_RULES = {
    "domestic_market": [
        "vàng miếng",
        "vàng nhẫn",
        "vàng sjc",
        "vàng trong nước",
        "sjc",
        "doji",
        "pnj",
        "bảo tín minh châu",
        "btmc",
    ],

    "fed_policy": [
        "fed",
        "federal reserve",
        "fomc",
        "interest rate",
        "interest rates",
        "rate cut",
        "rate cuts",
        "rate hike",
        "rate hikes",
        "monetary policy",
        "hawkish",
        "dovish",
        "cục dự trữ liên bang",
        "lãi suất",
        "cắt giảm lãi suất",
        "giảm lãi suất",
        "tăng lãi suất",
        "chính sách tiền tệ",
    ],

    "inflation_data": [
        "inflation",
        "cpi",
        "pce",
        "core pce",
        "consumer price index",
        "lạm phát",
    ],

    "usd_movement": [
        "usd",
        "u.s. dollar",
        "us dollar",
        "dollar",
        "dxy",
        "dollar index",
        "đồng usd",
        "đô la",
        "đồng đôla",
        "đồng bạc xanh",
    ],

    "bond_yield": [
        "treasury yield",
        "treasury yields",
        "bond yield",
        "bond yields",
        "10-year yield",
        "real yield",
        "real yields",
        "lợi suất trái phiếu",
        "trái phiếu kho bạc",
        "lợi suất kho bạc",
        "lợi suất mỹ",
    ],

    "geopolitical_risk": [
        "geopolitical",
        "safe haven",
        "safe-haven",
        "war",
        "conflict",
        "middle east",
        "ukraine",
        "russia",
        "địa chính trị",
        "trú ẩn an toàn",
        "tài sản trú ẩn",
        "chiến tranh",
        "xung đột",
        "trung đông",
        "nga",
    ],

    "tariff_trade": [
        "tariff",
        "tariffs",
        "trade war",
        "trade tension",
        "trade tensions",
        "thuế quan",
        "chiến tranh thương mại",
        "căng thẳng thương mại",
    ],

    "central_bank_demand": [
        "central bank buying",
        "central banks buy",
        "central bank demand",
        "central banks",
        "ngân hàng trung ương mua vàng",
        "nhu cầu ngân hàng trung ương",
        "ngân hàng trung ương",
    ],

    "economic_growth": [
        "gdp",
        "economic growth",
        "economic slowdown",
        "recession",
        "suy thoái",
        "tăng trưởng kinh tế",
        "kinh tế",
    ],

    "stock_market_risk": [
        "stock market",
        "stocks",
        "equities",
        "wall street",
        "s&p 500",
        "nasdaq",
        "dow jones",
        "chứng khoán",
        "cổ phiếu",
    ],

    "gold_price_update": [
        "gold price",
        "gold prices",
        "spot gold",
        "gold futures",
        "bullion",
        "precious metals",
        "giá vàng",
        "vàng thế giới",
        "kim loại quý",
    ],
}

EVENT_TYPE_PRIORITY = [
    "domestic_market",
    "fed_policy",
    "inflation_data",
    "usd_movement",
    "bond_yield",
    "geopolitical_risk",
    "tariff_trade",
    "central_bank_demand",
    "economic_growth",
    "stock_market_risk",
    "gold_price_update",
]


def classify_event_type(row):
    text = build_article_text(row)

    # Prefer domestic market if local symbols appear
    symbols = set(row.get("symbols", []))
    tags = set(row.get("tags", []))

    if any(symbol in symbols for symbol in ["SJC", "DOJI", "PNJ", "BTMC", "VND"]):
        return "domestic_market"

    if "fed" in tags:
        return "fed_policy"

    if "cpi" in tags or "pce" in tags or "inflation" in tags:
        return "inflation_data"

    if "usd" in tags or "dxy" in tags:
        return "usd_movement"

    if "bond_yield" in tags:
        return "bond_yield"

    if "geopolitical" in tags or "safe_haven" in tags:
        return "geopolitical_risk"

    if "tariff" in tags:
        return "tariff_trade"

    if "central_bank" in tags:
        return "central_bank_demand"

    if "stock_market" in tags:
        return "stock_market_risk"

    # Fallback by keyword rules
    for event_type in EVENT_TYPE_PRIORITY:
        keywords = EVENT_TYPE_RULES.get(event_type, [])
        if contains_any_keyword(text, keywords):
            return event_type

    return "other"

def classify_event_type_v2(row):
    text = build_article_text(row)

    symbols = set(row.get("symbols", []))
    tags = set(row.get("tags", []))

    # 1. Domestic market should be highest priority
    if any(symbol in symbols for symbol in ["SJC", "DOJI", "PNJ", "BTMC", "VND"]):
        return "domestic_market"

    # 2. Macro/event drivers
    if "fed" in tags or "interest_rate" in tags:
        return "fed_policy"

    if "cpi" in tags or "pce" in tags or "inflation" in tags:
        return "inflation_data"

    if "usd" in tags or "dxy" in tags:
        return "usd_movement"

    if "bond_yield" in tags:
        return "bond_yield"

    if "geopolitical" in tags or "safe_haven" in tags:
        return "geopolitical_risk"

    if "tariff" in tags:
        return "tariff_trade"

    if "central_bank" in tags:
        return "central_bank_demand"

    if "stock_market" in tags:
        return "stock_market_risk"

    # 3. Gold price update fallback
    if "gold_price" in tags or "world_gold" in tags or "GOLD" in symbols:
        return "gold_price_update"

    # 4. Keyword fallback
    for event_type in EVENT_TYPE_PRIORITY:
        keywords = EVENT_TYPE_RULES.get(event_type, [])
        if contains_any_keyword(text, keywords):
            return event_type

    return "other"


df_clean["event_type"] = df_clean.apply(classify_event_type_v2, axis=1)

df_clean["event_type"] = df_clean.apply(classify_event_type_v2, axis=1)

df_clean[[
    "source_name",
    "title",
    "symbols",
    "tags",
    "event_type",
    "relevance_score",
    "is_relevant",
]].head(30)

event_type_summary = (
    df_clean["event_type"]
    .value_counts()
    .reset_index()
)

event_type_summary.columns = ["event_type", "article_count"]
event_type_summary

event_type_by_source = (
    df_clean
    .groupby(["source_name", "event_type"])
    .size()
    .reset_index(name="article_count")
    .sort_values(["source_name", "article_count"], ascending=[True, False])
)

event_type_by_source

other_articles = df_clean[df_clean["event_type"] == "other"][
    [
        "source_name",
        "title",
        "summary",
        "symbols",
        "tags",
        "relevance_score",
        "is_relevant",
        "url",
    ]
].sort_values("relevance_score", ascending=False)

print("Other articles:", len(other_articles))
other_articles.head(30)

relevant_other_articles = df_clean[
    (df_clean["is_relevant"] == True)
    & (df_clean["event_type"] == "other")
][
    [
        "source_name",
        "title",
        "summary",
        "symbols",
        "tags",
        "relevance_score",
        "quality_score",
        "url",
    ]
].sort_values("relevance_score", ascending=False)

print("Relevant but event_type = other:", len(relevant_other_articles))
relevant_other_articles.head(30)

"""### 9. Sentiment Score

In this step, we compute a rule-based sentiment score from the perspective of gold price.

The score ranges from -1.0 to +1.0:

- positive score = bullish for gold
- negative score = bearish for gold
- near zero = neutral or unclear
"""

!pip install transformers torch sentencepiece accelerate

from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1
print("Device:", "GPU" if device == 0 else "CPU")

# English financial sentiment model
finbert_sentiment = pipeline(
    task="text-classification",
    model="ProsusAI/finbert",
    tokenizer="ProsusAI/finbert",
    device=device,
    truncation=True,
    max_length=512,
)

# Multilingual sentiment model, dùng cho Vietnamese
multi_sentiment = pipeline(
    task="text-classification",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    device=device,
    truncation=True,
    max_length=512,
)

def build_sentiment_input(row):
    title = clean_text(row.get("title", ""))
    summary = clean_text(row.get("summary", ""))

    text = f"{title}. {summary}".strip()

    if len(text) < 10:
        text = clean_text(row.get("content", ""))[:1000]

    return text[:1500]

def label_to_score(label, confidence):
    label = str(label).lower()

    if "positive" in label:
        return float(confidence)

    if "negative" in label:
        return -float(confidence)

    if "neutral" in label:
        return 0.0

    # fallback cho một số model dùng LABEL_0, LABEL_1, LABEL_2
    if label == "label_2":
        return float(confidence)
    if label == "label_0":
        return -float(confidence)
    if label == "label_1":
        return 0.0

    return 0.0

def predict_model_sentiment(row):
    text = build_sentiment_input(row)

    if not text:
        return {
            "model_sentiment_label": "neutral",
            "model_sentiment_confidence": 0.0,
            "sentiment_score": 0.0,
            "sentiment_model": "none",
        }

    language = clean_text(row.get("language", "")).lower()

    try:
        if language == "en":
            result = finbert_sentiment(text)[0]
            model_name = "finbert"
        else:
            result = multi_sentiment(text)[0]
            model_name = "multilingual_sentiment"

        label = result["label"]
        confidence = float(result["score"])
        score = label_to_score(label, confidence)

        # Không relevant thì kéo về gần neutral
        if not row.get("is_relevant", False):
            score *= 0.3

        return {
            "model_sentiment_label": label,
            "model_sentiment_confidence": confidence,
            "sentiment_score": round(max(min(score, 1.0), -1.0), 4),
            "sentiment_model": model_name,
        }

    except Exception as e:
        return {
            "model_sentiment_label": "error",
            "model_sentiment_confidence": 0.0,
            "sentiment_score": 0.0,
            "sentiment_model": str(e)[:80],
        }

from tqdm.auto import tqdm

tqdm.pandas()

sentiment_results = df_clean.progress_apply(predict_model_sentiment, axis=1)

sentiment_df = pd.DataFrame(list(sentiment_results))

df_clean["model_sentiment_label"] = sentiment_df["model_sentiment_label"]
df_clean["model_sentiment_confidence"] = sentiment_df["model_sentiment_confidence"]
df_clean["sentiment_score"] = sentiment_df["sentiment_score"]
df_clean["sentiment_model"] = sentiment_df["sentiment_model"]

df_clean[
    [
        "source_name",
        "language",
        "title",
        "event_type",
        "model_sentiment_label",
        "model_sentiment_confidence",
        "sentiment_score",
        "sentiment_model",
    ]
].head(30)

sentiment_by_source = (
    df_clean
    .groupby("source_name")
    .agg(
        total_articles=("id", "count"),
        avg_sentiment=("sentiment_score", "mean"),
        min_sentiment=("sentiment_score", "min"),
        max_sentiment=("sentiment_score", "max"),
        bullish_articles=("sentiment_score", lambda x: int((x > 0.1).sum())),
        bearish_articles=("sentiment_score", lambda x: int((x < -0.1).sum())),
        neutral_articles=("sentiment_score", lambda x: int(((x >= -0.1) & (x <= 0.1)).sum())),
    )
    .reset_index()
)

sentiment_by_source["avg_sentiment"] = sentiment_by_source["avg_sentiment"].round(4)

sentiment_by_source

"""### 10. Impact Score

In this step, we compute the potential impact level of each article on gold price.

The score ranges from 0.0 to 1.0:

- 0.0 = almost no impact
- 1.0 = very high impact

Impact score is different from sentiment score:

- sentiment_score measures direction
- impact_score measures strength
"""

def compute_impact_score(row):
    event_type = row.get("event_type", "other")
    relevance_score = float(row.get("relevance_score", 0.0) or 0.0)
    quality_score = float(row.get("quality_score", 0.0) or 0.0)
    is_relevant_value = bool(row.get("is_relevant", False))

    # Base score by event type
    event_base_impact = {
        "fed_policy": 0.85,
        "inflation_data": 0.85,
        "usd_movement": 0.80,
        "bond_yield": 0.80,
        "geopolitical_risk": 0.75,
        "central_bank_demand": 0.75,
        "tariff_trade": 0.65,
        "gold_price_update": 0.65,
        "domestic_market": 0.60,
        "stock_market_risk": 0.45,
        "economic_growth": 0.45,
        "other": 0.20,
    }

    impact = event_base_impact.get(event_type, 0.20)

    # Relevance adjustment
    impact = impact * (0.6 + 0.4 * relevance_score)

    # Quality adjustment
    if quality_score < 0.35:
        impact *= 0.6
    elif quality_score < 0.50:
        impact *= 0.85

    # Non-relevant articles should have low impact
    if not is_relevant_value:
        impact = min(impact, 0.20)

    return round(min(max(impact, 0.0), 1.0), 4)

df_clean["impact_score"] = df_clean.apply(compute_impact_score, axis=1)

df_clean[
    [
        "source_name",
        "title",
        "event_type",
        "quality_score",
        "relevance_score",
        "sentiment_score",
        "impact_score",
        "is_relevant",
    ]
].head(30)

impact_by_source = (
    df_clean
    .groupby("source_name")
    .agg(
        total_articles=("id", "count"),
        avg_impact=("impact_score", "mean"),
        min_impact=("impact_score", "min"),
        max_impact=("impact_score", "max"),
        high_impact_articles=("impact_score", lambda x: int((x >= 0.70).sum())),
        medium_impact_articles=("impact_score", lambda x: int(((x >= 0.40) & (x < 0.70)).sum())),
        low_impact_articles=("impact_score", lambda x: int((x < 0.40).sum())),
    )
    .reset_index()
)

impact_by_source["avg_impact"] = impact_by_source["avg_impact"].round(4)

impact_by_source

impact_by_event_type = (
    df_clean
    .groupby("event_type")
    .agg(
        total_articles=("id", "count"),
        avg_impact=("impact_score", "mean"),
        max_impact=("impact_score", "max"),
        avg_relevance=("relevance_score", "mean"),
        avg_quality=("quality_score", "mean"),
    )
    .reset_index()
    .sort_values("avg_impact", ascending=False)
)

impact_by_event_type["avg_impact"] = impact_by_event_type["avg_impact"].round(4)
impact_by_event_type["avg_relevance"] = impact_by_event_type["avg_relevance"].round(4)
impact_by_event_type["avg_quality"] = impact_by_event_type["avg_quality"].round(4)

impact_by_event_type

high_impact_articles = df_clean[
    df_clean["impact_score"] >= 0.70
][
    [
        "source_name",
        "title",
        "event_type",
        "quality_score",
        "relevance_score",
        "sentiment_score",
        "impact_score",
        "url",
    ]
].sort_values("impact_score", ascending=False)

high_impact_articles.head(30)

plt.figure(figsize=(10, 5))
sns.histplot(df_clean["impact_score"], bins=20, kde=True)
plt.title("Gold News Impact Score Distribution")
plt.xlabel("Impact Score")
plt.ylabel("Article Count")
plt.show()

"""### 11. Final Audit and Export Enriched Data

In this step, we validate the enriched dataset and export it to CSV.

The enriched dataset contains:

- cleaned text
- normalized URL
- recomputed hashes
- duplicate flag
- quality score
- relevance score
- symbols
- tags
- entities
- event type
- sentiment score
- impact score
"""

df_clean["updated_at"] = datetime.now()

df_clean[["id", "updated_at"]].head()

required_enriched_fields = [
    "id",
    "title",
    "summary",
    "content",
    "source_name",
    "url",
    "canonical_url",
    "published_at",
    "content_hash",
    "title_hash",
    "is_duplicate",
    "quality_score",
    "relevance_score",
    "is_relevant",
    "symbols",
    "tags",
    "entities",
    "event_type",
    "sentiment_score",
    "impact_score",
    "updated_at",
]

final_audit = {}

for col in required_enriched_fields:
    if col not in df_clean.columns:
        final_audit[col] = "MISSING_COLUMN"
    else:
        if col in ["symbols", "tags", "entities"]:
            final_audit[col] = int(df_clean[col].apply(lambda x: len(x) == 0 if isinstance(x, list) else True).sum())
        else:
            final_audit[col] = int(df_clean[col].isna().sum())

final_audit_df = pd.DataFrame(
    list(final_audit.items()),
    columns=["field", "missing_or_empty_count"]
)

final_audit_df

mvp_checks = {
    "content_hash_not_empty": int((df_clean["content_hash"].fillna("").astype(str).str.len() > 0).sum()),
    "quality_score_not_null": int(df_clean["quality_score"].notna().sum()),
    "relevance_score_not_null": int(df_clean["relevance_score"].notna().sum()),
    "is_relevant_not_null": int(df_clean["is_relevant"].notna().sum()),
    "event_type_not_empty": int((df_clean["event_type"].fillna("").astype(str).str.len() > 0).sum()),
    "sentiment_score_not_null": int(df_clean["sentiment_score"].notna().sum()),
    "impact_score_not_null": int(df_clean["impact_score"].notna().sum()),
    "total_rows": len(df_clean),
}

mvp_checks

final_summary = {
    "total_articles": len(df_clean),
    "relevant_articles": int(df_clean["is_relevant"].sum()),
    "duplicate_articles": int(df_clean["is_duplicate"].sum()),
    "avg_quality_score": round(df_clean["quality_score"].mean(), 4),
    "avg_relevance_score": round(df_clean["relevance_score"].mean(), 4),
    "avg_sentiment_score": round(df_clean["sentiment_score"].mean(), 4),
    "avg_impact_score": round(df_clean["impact_score"].mean(), 4),
    "high_impact_articles": int((df_clean["impact_score"] >= 0.70).sum()),
    "embed_candidate_articles_quality_035": int(
        (
            (df_clean["is_relevant"] == True)
            & (df_clean["quality_score"] >= 0.35)
            & (df_clean["is_duplicate"] == False)
        ).sum()
    ),
    "embed_candidate_articles_quality_050": int(
        (
            (df_clean["is_relevant"] == True)
            & (df_clean["quality_score"] >= 0.50)
            & (df_clean["is_duplicate"] == False)
        ).sum()
    ),
}

pd.DataFrame([final_summary]).T.rename(columns={0: "value"})

import json

df_export = df_clean.copy()

for col in ["symbols", "tags", "entities"]:
    df_export[col] = df_export[col].apply(
        lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, list) else json.dumps([], ensure_ascii=False)
    )

export_columns = [
    "id",
    "title",
    "summary",
    "content",
    "source_name",
    "source_type",
    "author",
    "url",
    "canonical_url",
    "published_at",
    "crawled_at",
    "updated_at",
    "category",
    "language",
    "region",
    "event_type",
    "symbols",
    "tags",
    "entities",
    "sentiment_score",
    "impact_score",
    "relevance_score",
    "content_hash",
    "title_hash",
    "is_duplicate",
    "quality_score",
    "is_relevant",
    "raw_payload",
    "extra_metadata",
]

existing_export_columns = [col for col in export_columns if col in df_export.columns]

df_export = df_export[existing_export_columns]

df_export.head()

OUTPUT_PATH = "/content/gold_news_enriched.csv"

df_export.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

print("Exported:", OUTPUT_PATH)
print("Rows:", len(df_export))
print("Columns:", len(df_export.columns))

from google.colab import files

files.download(OUTPUT_PATH)